/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['mass星球-火箭']: THREE.Mesh
    ['mass星球-火箭发光体']: THREE.Mesh
  }
  materials: {
    plant1: THREE.MeshPhysicalMaterial
    light: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/planet_01.glb'
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <directionalLight
        intensity={1}
        color="#ff412a"
        position={[35.33, 10.09, 64.93]}
        rotation={[-0.15, 0.49, -3.07]}
      />
      <rectAreaLight
        intensity={10}
        color="#40DBFF"
        position={[-18, 9, 9]}
        rotation={[0, 0, 0]}
        scale={[4, 8, 1]}
      />

      <mesh
        geometry={nodes['mass星球-火箭'].geometry}
        material={materials.plant1}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['mass星球-火箭发光体'].geometry}
        material={materials.light}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/planet_01.glb')
